// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartDesk.Api.Data;

#nullable disable

namespace SmartDesk.Api.Migrations
{
    [DbContext(typeof(SmartDeskContext))]
    [Migration("20260730161248_AddUsersTable")]
    partial class AddUsersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartDesk.Api.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 10001,
                            CreatedAt = new DateTime(2026, 7, 10, 8, 23, 0, 0, DateTimeKind.Utc),
                            Customer = "Lars Nielsen",
                            Email = "lars@example.com",
                            Status = "open",
                            Subject = "Front wheel is making a grinding noise",
                            Urgency = "HIGH"
                        },
                        new
                        {
                            Id = 10002,
                            CreatedAt = new DateTime(2026, 7, 11, 10, 5, 0, 0, DateTimeKind.Utc),
                            Customer = "Sofia Berg",
                            Email = "sofia@example.com",
                            Status = "open",
                            Subject = "Invoice shows wrong VAT amount",
                            Urgency = "LOW"
                        },
                        new
                        {
                            Id = 10003,
                            CreatedAt = new DateTime(2026, 7, 12, 14, 30, 0, 0, DateTimeKind.Utc),
                            Customer = "Mikkel Holm",
                            Email = "mikkel@example.com",
                            Status = "resolved",
                            Subject = "Battery not charging past 40 percent",
                            Urgency = "MEDIUM"
                        });
                });

            modelBuilder.Entity("SmartDesk.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "staff@smartdesk.com",
                            PasswordHash = "$2a$11$rBnNmMDDqMKRRSSgLBMxuuWfhGXEzGPXcFJQjhIlkVpkHqIQJE5Zy",
                            Role = "staff"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
